import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f5f7',
  },
  content: {
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 48,
  },
  title: {
    fontSize: 20,
    fontWeight: '600',
    marginBottom: 32,
  },
  label: {
    fontSize: 14,
    color: '#666',
    marginBottom: 4,
  },
  status: {
    fontSize: 28,
    fontWeight: '700',
    marginBottom: 12,
  },
  error: {
    fontSize: 13,
    color: '#c0392b',
    marginBottom: 20,
  },
  buttonRow: {
    width: '100%',
    gap: 12,
  },
  button: {
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: 'center',
    backgroundColor: '#fff',
  },
  buttonActive: {
    backgroundColor: '#111',
    borderColor: '#111',
  },
  buttonText: {
    fontSize: 16,
    fontWeight: '500',
    color: '#111',
  },
  buttonTextActive: {
    color: '#fff',
  },
  sectionTitleRow: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 40,
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
  },
  sectionTitleStandalone: {
    width: '100%',
    marginTop: 32,
    marginBottom: 12,
  },
  viewAllLink: {
    fontSize: 14,
    fontWeight: '500',
    color: '#1a5276',
  },
  manageContactsLink: {
    width: '100%',
    alignItems: 'flex-end',
    marginTop: 12,
  },
  deleteButtonRow: {
    width: '100%',
    flexDirection: 'row',
    gap: 10,
    marginBottom: 20,
  },
  deleteButtonHalf: {
    flex: 1,
    marginBottom: 0,
  },
  deleteOldButton: {
    width: '100%',
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#c0392b',
    alignItems: 'center',
    marginBottom: 20,
  },
  deleteOldButtonText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#c0392b',
    textAlign: 'center',
  },
  emptyText: {
    fontSize: 14,
    color: '#666',
    alignSelf: 'flex-start',
  },
  callList: {
    width: '100%',
    gap: 12,
  },
  callCard: {
    borderWidth: 1,
    borderColor: '#e0e0e0',
    borderRadius: 10,
    padding: 14,
    backgroundColor: '#fff',
  },
  callCardDismissed: {
    opacity: 0.5,
  },
  callCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  callNameColumn: {
    flexShrink: 1,
  },
  callName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#111',
  },
  callCompany: {
    fontSize: 13,
    color: '#666',
    marginTop: 2,
  },
  callTime: {
    fontSize: 12,
    color: '#888',
  },
  callReason: {
    fontSize: 14,
    color: '#333',
    marginTop: 6,
  },
  callRecommendation: {
    fontSize: 13,
    color: '#1a5276',
    fontWeight: '500',
    marginTop: 6,
  },
  callMetaRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
  },
  callBadgeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    flexShrink: 1,
    gap: 8,
    alignItems: 'center',
  },
  decisionBadge: {
    fontSize: 11,
    fontWeight: '600',
    color: '#444',
    backgroundColor: '#eee',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  decisionBadgeTransfer: {
    color: '#fff',
    backgroundColor: '#1a5276',
  },
  decisionBadgeReject: {
    color: '#fff',
    backgroundColor: '#c0392b',
  },
  decisionBadgeFailed: {
    color: '#fff',
    backgroundColor: '#946c00',
  },
  callTypeBadge: {
    fontSize: 11,
    fontWeight: '500',
    color: '#444',
    backgroundColor: '#eee',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    textTransform: 'capitalize',
  },
  callPriorityBadge: {
    fontSize: 11,
    fontWeight: '600',
    color: '#666',
    backgroundColor: '#eee',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    textTransform: 'capitalize',
  },
  callPriorityHigh: {
    color: '#fff',
    backgroundColor: '#c0392b',
  },
  callUrgency: {
    fontSize: 12,
    color: '#c0392b',
    fontWeight: '500',
  },
  callStatus: {
    fontSize: 12,
    color: '#888',
    textTransform: 'capitalize',
  },
  callActionRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 12,
  },
  callActionButton: {
    flex: 1,
    paddingVertical: 9,
    borderRadius: 8,
    alignItems: 'center',
    backgroundColor: '#111',
  },
  callActionGhost: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#ccc',
  },
  callActionText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#fff',
  },
  callActionGhostText: {
    color: '#444',
  },
  activeRuleBanner: {
    width: '100%',
    marginTop: 16,
    borderWidth: 1,
    borderColor: '#1a5276',
    borderRadius: 10,
    padding: 12,
    backgroundColor: '#eaf1f8',
  },
  activeRuleText: {
    fontSize: 14,
    fontStyle: 'italic',
    color: '#1a5276',
  },
  activeRuleExpiry: {
    fontSize: 12,
    color: '#1a5276',
    marginTop: 4,
  },
  naturalInputBox: {
    width: '100%',
    borderWidth: 1,
    borderColor: '#e0e0e0',
    borderRadius: 10,
    padding: 14,
    backgroundColor: '#fff',
    marginBottom: 24,
  },
  naturalInputField: {
    minHeight: 60,
    textAlignVertical: 'top',
  },
  confirmSummary: {
    fontSize: 14,
    color: '#333',
    marginBottom: 10,
  },
  addContactForm: {
    width: '100%',
    borderWidth: 1,
    borderColor: '#e0e0e0',
    borderRadius: 10,
    padding: 14,
    backgroundColor: '#fff',
    marginBottom: 24,
  },
  textInput: {
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 15,
    marginBottom: 10,
  },
  formLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#666',
    marginBottom: 6,
    marginTop: 4,
  },
  chipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 10,
  },
  chip: {
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: '#fff',
  },
  chipActive: {
    backgroundColor: '#111',
    borderColor: '#111',
  },
  chipText: {
    fontSize: 12,
    fontWeight: '500',
    color: '#444',
    textTransform: 'capitalize',
  },
  chipTextActive: {
    color: '#fff',
  },
  addContactButton: {
    marginTop: 6,
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: 'center',
    backgroundColor: '#111',
  },
  contactCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e0e0e0',
    borderRadius: 10,
    padding: 14,
    backgroundColor: '#fff',
  },
  contactBadgeColumn: {
    gap: 6,
    alignItems: 'flex-end',
  },
  deleteContactLink: {
    fontSize: 13,
    fontWeight: '500',
    color: '#c0392b',
    marginLeft: 12,
  },
  // Call Details screen
  detailName: {
    fontSize: 22,
    fontWeight: '700',
    color: '#111',
    marginTop: 8,
  },
  detailSection: {
    width: '100%',
    marginTop: 18,
  },
  // Settings screen
  settingsCard: {
    width: '100%',
    borderWidth: 1,
    borderColor: '#e0e0e0',
    borderRadius: 10,
    padding: 14,
    backgroundColor: '#fff',
    marginBottom: 14,
    gap: 10,
  },
  settingsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  settingsLabel: {
    fontSize: 13,
    color: '#666',
  },
  settingsValue: {
    fontSize: 15,
    fontWeight: '600',
    color: '#111',
    marginTop: 2,
  },
  settingsOk: {
    fontSize: 13,
    fontWeight: '600',
    color: '#1e7d32',
  },
  settingsMissing: {
    fontSize: 13,
    fontWeight: '600',
    color: '#c0392b',
  },
  // Rules screen
  rulesNote: {
    fontSize: 13,
    color: '#666',
    marginTop: 16,
  },
  rulesSection: {
    width: '100%',
  },
  rulesTable: {
    width: '100%',
    borderWidth: 1,
    borderColor: '#e0e0e0',
    borderRadius: 10,
    backgroundColor: '#fff',
    overflow: 'hidden',
  },
  rulesRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  rulesType: {
    fontSize: 14,
    color: '#333',
    textTransform: 'capitalize',
    flexShrink: 1,
    paddingRight: 12,
  },
  rulesAction: {
    fontSize: 13,
    fontWeight: '600',
    color: '#1a5276',
  },
  rulesEditRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
    backgroundColor: '#f9f9f9',
  },
});
